### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by timeflow-lab** [xhuang31/Label-Informed-Attributed-Network-Embedding#1]
Thank you for your  sharing. In the optimization algorithm of the paper, the second order derivative is computed and is verified that it is should always be positive semidefinite. As far as I know, a function should have the minimum value if the second order derivative is positive semidefinite. Why the maximum value can be got when the second order derivative is positive semidefinite in this paper

**Comment by xhuang31** [comment]
Thanks for your interest.

Give that the second order derivative is positive semidefinite, e.g., f(x) = x^2, or f(x) = -x^2,

 then if the first order derivative is positive, the function is convex and would have min, like f(x) = x^2,
         if the first order derivative is negative, the function is concave and would have max, like f(x) = -x^2.
